### ISSUE TITLE
用語について

### ISSUE THREAD

**Issue by takahashim** [HackCamp/guideline#1]
イベントのガイドライン・Code of Conduct等に興味があり、拝読いたしました。

こちらのガイドラインでは、例えば運営者について、「運営者」「イベント運営者」「オーガナイザー」「運営事務局」といった同じようなことを指す用語が使われているようです。同様に、スタッフについても、「スタッフ」「会場スタッフ」「運営スタッフ」「ボランティア」などが使われています。

これらは何か区別があるのでしょうか？　特にないのであれば、統一した方がよいのではないかと思いました（もし、区別に意味があるのであればすみません）。

**Comment by halsk** [comment]
コメントありがとうございます！区別があるわけではありませんので、統一するようにしたいと思います。

**Comment by halsk** [comment]
表記を修正させていただきました。ありがとうございました。

**Comment by takahashim** [comment]
@halsk 素早いご対応ありがとうございました！
こういう細かいところも見つけ次第、都度ご報告した方がよいでしょうか？（運用にあたってはあまり本質的なところではないかとも思うので、ちょっとためらっております）

**Comment by halsk** [comment]
差し支えなければ、是非ご報告ください！出来る限り反映します。

**Comment by takahashim** [comment]
お返事ありがとうございます、では都度pull requestでお送りします（しました）。
こちらは閉じておきますね。
